name: flutter_boilerplate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^3.1.3
  dartx: ^1.0.0
  device_preview: ^0.8.0
  flutter_state_notifier: ^0.7.1
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.0.0
  functional_listener: ^2.0.2
  logger: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  provider: ^6.0.1
  responsive_builder: ^0.4.1
  rx_notifier: ^1.1.0
  rxdart: ^0.27.3
  state_notifier: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  freezed: ^1.0.0
  json_serializable: ^6.0.1

dependency_overrides:
  freezed_annotation: ^1.0.0
  provider: ^6.0.1

flutter:
  uses-material-design: true
